---
abstract: 'time the different stages of an HTTP request'
author:
  - 'Simon Wistow <simon@thegestalt.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWPx-TimedHTTP
provides:
  LWPx::TimedHTTP:
    file: lib/LWPx/TimedHTTP.pm
    version: 1.6
  LWPx::TimedHTTP::Socket:
    file: lib/LWPx/TimedHTTP.pm
    version: 0
  LWPx::TimedHTTP::https:
    file: lib/LWPx/TimedHTTP.pm
    version: 0
  LWPx::TimedHTTP::https::Socket:
    file: lib/LWPx/TimedHTTP.pm
    version: 0
requires:
  HTTP::Daemon: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Test::More: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.6
