---
name: LWPx-TimedHTTP
version: 1.5
author:
  - 'Simon Wistow <simon@thegestalt.org>'
abstract: time the different stages of an HTTP request
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTTP::Daemon: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Test::More: 0
  Time::HiRes: 0
provides:
  LWPx::TimedHTTP:
    file: lib/LWPx/TimedHTTP.pm
    version: 1.5
  LWPx::TimedHTTP::Socket:
    file: lib/LWPx/TimedHTTP.pm
  LWPx::TimedHTTP::https:
    file: lib/LWPx/TimedHTTP.pm
  LWPx::TimedHTTP::https::Socket:
    file: lib/LWPx/TimedHTTP.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
